dhlab/api/dhlab_api.py, setup.py
lagt til fulltext som parameter til get_document_corpus
=> Fulltext metadata

dhlab/api/dhlab_api.py
changed frequency - fixing a bug in the communication with the server
=> fix: frequency

dhlab/api/dhlab_api.py, dhlab/text/corpus.py
Evaluate wordbags against a corpus
=> feat: code for word evaluations

.gitignore, dhlab/text/conc_coll.py, dhlab/text/corpus.py
Reverts NationalLibraryOfNorway/DHLAB#76
=> fix: Revert "Larsm"

dhlab/text/corpus.py
need to be able to work with dataframe with urns
=> fix(corpus) : extend_from_identifiers

dhlab/ngram/nb_ngram.py
forrige endring så ikke ut til å virke
=> fix: revert ngram_conv()

dhlab/ngram/nb_ngram.py, dhlab/ngram/ngram.py
added relative parameter to class Ngram
=> fix: relative and absolute

dhlab/api/dhlab_api.py
The first iteration of searching and finding images
=> feat: added image search in bokhylla books to api

dhlab/__init__.py, dhlab/text/conc_coll.py, dhlab/text/corpus.py, dhlab/text/dhlab_object.py
* Instantiate Corpus w/o params gives an empty corpus class
* classmethod from_df creates Corpus from DataFrame
Legger til funksjon i Corpus - tillater å lage "tomt" korpus og å legger til metode for å typecaste DataFrame til Corpus
=> feat(Corpus): allow empty Corpus and construct df

dhlab/api/dhlab_api.py, dhlab/text/conc_coll.py, dhlab/text/corpus.py, dhlab/text/dhlab_object.py
Fixes to the following DhlabObj methods:
* to_csv()
* to_excel()
* from_csv()
=> fix(dhlab_object): fix DhlabObj methods

dhlab/text/conc_coll.py, dhlab/text/corpus.py, dhlab/text/dhlab_object.py, dhlab/text/utils.py, docs/DOCS_CHANGELOG.md
Add conc, coll and counts as methods for Corpus.
Create utils.py for text
=> Feat(corpus): conc coll methods

dhlab/api/dhlab_api.py, dhlab/text/geo_data.py
- (dhlab_api.show_spacy_models): return empty list
- (text.geo_data.GeoData): add private method to call for  place names with spacy, with error handling of user input and empty return values.
=> fix: handle API errors

dhlab/api/nb_ngram_api.py, dhlab/ngram/ngram.py, dhlab/text/corpus.py, dhlab/text/dispersion.py, dhlab/visualize/cloud.py, dhlab/wordbank/wordbank.py
* Add kwargs to Ngram - allows to modify plot from constructor
* Creates dhlab.visualize package containing visualization tools
=> feat(visualize, ngram):

dhlab/text/corpus.py, dhlab/text/utils.py
* from_identifiers() -> Classmethod
* fix(Corpus from identifiers)
* Depreciation warning EmptyCorpus, Corpus_from_identifiers
* add Series to urnlist
=> feat(corpus):

dhlab/future/corpus_conc_coll.py
add dataframe subclasses to future module
=> feat(future):

dhlab/text/conc_coll.py, tests/test_Counts.py
* counts accepts urnlist
* add pytest for counts
=> fix(counts):

dhlab/api/dhlab_api.py
Functionality for imagination - accessed via get in dhlab Flask server
=> added comment

.github/workflows/release.yml
Oppgrader actions og poetry-installasjon i release.yml
=> Ci patch 1

.github/workflows/CI.yml, .github/workflows/docs.yml, .github/workflows/test.yml, docs/source/index.md, pyproject.toml
Resolves https://github.com/NationalLibraryOfNorway/DHLAB/issues/225.
Also makes https://github.com/NationalLibraryOfNorway/DHLAB/pull/223 pass CI.
Replaces #227 (see https://github.com/NationalLibraryOfNorway/DHLAB/pull/227#pullrequestreview-2551732016)
=> Update Python from 3.9 to 3.10

.github/workflows/CI.yml
=> CI: Test all supported python versions

dhlab/api/dhlab_api.py, dhlab/api/nb_ngram_api.py, dhlab/api/utils.py, tests/api/nb_ngram_api/test_get_ngram.py, tests/api/nb_ngram_api/test_make_word_graph.py
=> Handle server errors

dhlab/api/dhlab_api.py
=> Fix dhlab api errors

.gitignore, dhlab/text/chunking.py, dhlab/text/conc_coll.py, dhlab/text/corpus.py, dhlab/text/parse.py
=> Add type hints
